{"name": "test_blog_page_case2", "status": "skipped", "statusDetails": {"message": "XFAIL 标记为预期失败\n\nAssertionError: assert '博客园 - 开发者的网上家园' == '博客园1 - 开发者的网上家园'\n  - 博客园1 - 开发者的网上家园\n  ?    -\n  + 博客园 - 开发者的网上家园", "trace": "self = <test_dir.test_blog_home.Test_Home_Blog object at 0x000002012E4929C8>\nbrowser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"c762a1c5c9631f7292aadcbf913c3f53\")>\n\n    @allure.story('首页页面显示错误测试')\n    @pytest.mark.home\n    @pytest.mark.xfail(condition=True, reason='标记为预期失败')\n    @pytest.mark.run(order=1)\n    def test_blog_page_case2(self, browser):\n        \"\"\"\n        名称：博客园首页页面测试\n        步骤：\n        1、打开博客园页面\n        2、检查首页页面\n        检查点：\n        * 检查首页页面是否包含关键字。\n        \"\"\"\n        bp = BlogPage(browser)\n        with allure.step('打开url'):\n            print(bp.url)\n            bp.open(bp.url)\n        with allure.step('等待首页页面显示'):\n            bp.get_display(bp.regist_element)\n        with allure.step('判断显示是否正确'):\n            title = browser.title\n>           assert title == \"博客园1 - 开发者的网上家园\"\nE           AssertionError: assert '博客园 - 开发者的网上家园' == '博客园1 - 开发者的网上家园'\nE             - 博客园1 - 开发者的网上家园\nE             ?    -\nE             + 博客园 - 开发者的网上家园\n\ntest_dir\\test_blog_home.py:60: AssertionError"}, "description": "\n        名称：博客园首页页面测试\n        步骤：\n        1、打开博客园页面\n        2、检查首页页面\n        检查点：\n        * 检查首页页面是否包含关键字。\n        ", "steps": [{"name": "打开url", "status": "passed", "start": 1645858780945, "stop": 1645858782979}, {"name": "等待首页页面显示", "status": "passed", "start": 1645858782979, "stop": 1645858782996}, {"name": "判断显示是否正确", "status": "failed", "statusDetails": {"message": "AssertionError: assert '博客园 - 开发者的网上家园' == '博客园1 - 开发者的网上家园'\n  - 博客园1 - 开发者的网上家园\n  ?    -\n  + 博客园 - 开发者的网上家园\n", "trace": "  File \"G:\\work_python\\ui_autotest_3\\test_dir\\test_blog_home.py\", line 60, in test_blog_page_case2\n    assert title == \"博客园1 - 开发者的网上家园\"\n"}, "start": 1645858782996, "stop": 1645858782999}, {"name": "添加失败截图...", "status": "passed", "attachments": [{"name": "失败截图", "source": "17dd29ab-501c-4176-a4de-0eced9d087ad-attachment.png", "type": "image/png"}], "start": 1645858783046, "stop": 1645858783320}], "attachments": [{"name": "log", "source": "ca780057-f31c-4311-8d94-0fdc9e2e20be-attachment.txt", "type": "text/plain"}], "start": 1645858780944, "stop": 1645858782999, "uuid": "8412087b-640b-4662-9d2c-cc8607ec8aa5", "historyId": "244805c7da1185d41124941f464167b8", "testCaseId": "fc96a71c7a5eed83c04f8d09d7dd5451", "fullName": "test_dir.test_blog_home.Test_Home_Blog#test_blog_page_case2", "labels": [{"name": "feature", "value": "博客园首页测试"}, {"name": "story", "value": "首页页面显示错误测试"}, {"name": "tag", "value": "@pytest.mark.xfail(condition=True, reason='标记为预期失败')"}, {"name": "tag", "value": "home"}, {"name": "tag", "value": "run(order=1)"}, {"name": "parentSuite", "value": "test_dir"}, {"name": "suite", "value": "test_blog_home"}, {"name": "subSuite", "value": "Test_Home_Blog"}, {"name": "host", "value": "WP"}, {"name": "thread", "value": "2468-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_dir.test_blog_home"}]}